import 'package:api_exem_advance/screen/home/provider/home_provider.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../model/home_model.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  HomeProvider? providerW;
  HomeProvider? providerR;
  @override
  void initState() {
    super.initState();
    context.read<HomeProvider>().getQuotesAPI();
  }
  @override
  Widget build(BuildContext context) {
    providerW=context.watch<HomeProvider>();
    providerR=context.read<HomeProvider>();
    return Scaffold(
      appBar: AppBar(title: Text("QuotesApp"),),
      body: FutureBuilder(
        future: providerW!.modelList,
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text("${snapshot.error}"));
          } else if (snapshot.hasData) {
            Autogenerated? model = snapshot.data;
            providerR!.resultsList.addAll(model!.results!);

            if (model == null) {
              return const Center(child: Text("not available"));
            } else if (providerR!.resultsList.isEmpty) {
              return const Center(child: Text("search another topic"));
            } else {
              return Expanded(
                child: GridView.builder(
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2,mainAxisExtent: 260,),
                  itemCount: providerW!.resultsList.length,
                  itemBuilder: (BuildContext context, int index) {
                    return Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Column(
                          children: [
                            InkWell(
                              onTap: () {
                                Navigator.pushNamed(context,"/detail",arguments: Autogenerated());
                              },
                              child: Card(
                                child: Container(
                                  height: 250,
                                    width: 250,
                                    decoration: const BoxDecoration(
                                      gradient: LinearGradient(
                                        colors: [
                                          Color(0xffae1232),
                                          Color(0xff430d36),
                                        ],
                                      ),
                                    ),
                                    child: Center(child: Text("${providerW!.resultsList[index].author}",style: const TextStyle(fontSize: 20,color: Colors.white,fontWeight: FontWeight.bold),),),),
                              ),
                            ),

                          ],
                        )
                      ],
                    );
                  },
                ),
              );
            }
          }

          return const Center(child: CircularProgressIndicator());
        },
      ),
    );
  }
}

