import 'package:api_exem_advance/utils/quotes_api_helper.dart';
import 'package:flutter/material.dart';

import '../model/home_model.dart';

class HomeProvider with ChangeNotifier {
  Future<Autogenerated?>? modelList;
  List<Results>resultsList=[];

  void getQuotesAPI() {
    QuotesApiHelper helper = QuotesApiHelper();
    modelList = helper.quotesAPI();
    modelList!.then(
      (value) {
        if (value != null) {
          notifyListeners();
        }
      },
    );
  }
}
