import 'dart:convert';

import 'package:http/http.dart' as http;

import '../screen/home/model/home_model.dart';
class QuotesApiHelper
{
  Future<Autogenerated ?>? quotesAPI() async {
    String? link="https://api.quotable.io/quotes?page=1&_gl=1*nmqqjw*_ga*Mjk0MzAzODkwLjE3MjMwMDg1ODQ.*_ga_ZCYG64C7PL*MTcyMzE3MDYwOC40LjEuMTcyMzE3MDkxMi4wLjAuMA..";
  var response = await http.get(Uri.parse(link));
  if(response.statusCode==200)
    {
      var json =await jsonDecode (response.body);
      var  model=Autogenerated.fromJson(json);
      return model;
    }
  return null;
  }
}